import type { Metadata } from "next";
import "./globals.css";
import { VercelToolbar } from '@vercel/toolbar/next';
import { Header } from "@/components/Header/Header";
import { Footer } from "@/components/Footer/Footer";
import { ThemeProvider } from "@/components/theme/theme-provider"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {

  const shouldInjectToolbar = process.env.NODE_ENV === 'development';
  // const banner = await showBanner();
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <Header />
          {children}
          {shouldInjectToolbar && <VercelToolbar />}
          <Footer />
        </ThemeProvider>

      </body>
    </html>
  );
}
